lang = {
    'en': {
        ':ENG': 'EN',
        ':DE': 'DE',
        ':en': 'en',
        ':de': 'de',
        ':ENGM': 'EN',
        ':DEM': 'DE',
        ':enM': 'en',
        ':deM': 'de',
        ':home': 'Home',
        ':OurServices': 'Our Services',
        ':AboutUs': 'About Us',
        ':ContactUs': 'Contact Us',
        ':homeM': 'Home',
        ':OurServicesM': 'Our Services',
        ':AboutUsM': 'About Us',
        ':ContactUsM': 'Contact Us',
        ':herosubtitle': 'SOURCING MANAGEMENT ON THE',
        ':herosubtitleNL': 'NEXT LEVEL',
        ':heroparagraph': 'We solve problems,  We get things done,  We set the trend in sourcing management',
        ':scroll': 'scroll',
        ':maintitle': 'ABOUT US',
        ':mainparagraph': 'As The Age of Man dominates the world with dynamic advancements in technology and services, <span style="color: #004A94;"> InnoChain Solutions (ICS)</span> submits to be your topmost procurement solutions-provider backed up with high-end information and communications technology experience services.',
        ':Learnmore': 'Find out more',
        ':fristcardtitle': 'Our Vision',
        ':fristcardtext': 'InnoChain Solutions envisions to be the leading global convergence point in providing top quality procurement management services bundled with high digital integration, that boosts and upgrades different kinds of businesses, professions, and even personal endeavors -- to reaching the road to fulfillment, growth, and success.',
        ':secondcardtitle': 'Our Mission',
        ':secondcardtext': 'InnoChain Solutions commits to be among the topmost procurement solution-providers, technology-upgraders, and digital systems-enhancers, administering new and fresh proactive approaches with our best practices protocols to perfectly address and solve diverse needs and unique demands from beginning entrepreneurs, growing companies, and booming business -- with no money lost, no time lapsed, and no effort wasted -- just high performance, optimized customizations, big results, and many operations done by only using very few resources at low costs.',
        ':thirdcardtitle': 'Our Trademarks',
        ':thirdcardtextleft': '- Digital and Technological. <br/> - Fast and Wise.<br/> - Innovative and Creative.<br/> - Safe and Secured.<br/> - Reasonable and Economical.<br/> - Efficient and Proficient.<br/> - Systematic and Strategic.',
        ':thirdcardtextright': '- Functional and Operational.<br/> - Confident and Competent.<br/> - Collaborative and Operative.<br/> - Reliable and Flexible.<br/> - Convenient and Comfortable.<br/> - Sustainable and Accessible.<br/> - Committed and Disciplined.<br/>',
        ':servicestitle': 'SERVICES',
        ':SourcingManagementServices': 'Sourcing Management <br/> Services',
        ':SourcingCommodities': 'Sourcing Commodities',
        ':FamilyOfficeServicesSourcing': 'Family Office Services <br/> Sourcing',
        ':ITServices': 'IT Services',
        ':ConsultingServices': 'Consulting Services',
        ':HealthCare': 'Health Care',
        ':ContactUS': 'Contact us',
        ':Contactinfo': 'Contact info',
        ':Message': 'Message',
        ':submit' : 'Submit',
        ':AboutUsTitle' : 'About us',
        ':FristAboutText' : '<span style="font-size: 30px; color: #004A94;">InnoChain Solutions (ICS) </span>is a pro-studded, private, and independent global company built and  joint by a collaboration of procurement services specialists and digital technology experts from top companies in the world. With our work experiences and accumulated researches for many years in our respective job fields, we are fully equipped to assure our clients that we deliver with caliber -- a set of integrated, innovative, comprehensive, and quality end-to-end high technology procurement capabilities, to tailor-fit with care various demands and diverse needs of the global markets and businesses, where substantial key end results and key saving targets are guaranteed.',
        ':SecondAboutText' : '<i>"InnoChain Solutions company is a collaboration of procurement specialists and digital-technology experts around the globe." <br/> - ICS Executive President. -</i>',
        ':ManagementServicesFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span>invests in bulks of multiple procurement services. Using our wide expertise, thorough knowledge, and constant innovation, we are keen in providing our clients, with fully integrated supply management services to give you a complete full source-to-settle and end-to-end solutions towards efficient scale operation system and substantial production gains, which result to optimum cost advantages and cost savings.',
        ':ManagementServicesSecondText' : 'COVERAGE: <br/>-  Supply Chain Management<br/>-  Supplier Networks<br/>-  Sourcing<br/>-  Commodities<br/>-  Services and Indirect Spend',
        ':ManagementServicesThirdText' : '<i style="color: #004A94;">"InnoChain Solutions spots the missing links and the weak units which hinder your business to run smooth and to work in progress."</i>',
        ':SourcingFirstText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span> upholds its reputation  and strengthens its connection and ties with various global industries to better serve clients, so we can exceed what is expected of us. With our commodities sourcing expertise, we support our clients to have problem-free and stress-free work and business experience, meeting deadlines and being able to focus on critical parts of the business. ',
        ':SourcingSecondText' : 'Coverage:<br/>-  Agricultural<br/>-  Energy<br/>-  Metals<br/>-  Livestock<br/>-  Logistics',
        ':SourcingThirdText' : '<i style="color: #004A94;">"InnoChain Solutions has wide and strong business connections around the globe to give you the perfect solutions."</i>',
        ':FamilyServicesFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span>comprises of flexible and network business intelligences that innovatively frame and find new ways to spot the perfect-fit and tailor-fit category services, strategies, and solutions for our clientsso you can extract more value out of the supply chain. ',
        ':FamilyServicesSecondText' : 'Coverage:<br/>-  Demand Management<br/>-  Sourcing Strategies<br/>-  Best Cost Sourcing Practices<br/>-  Supply Chain Management<br/>-  Market Assessment<br/>-  Category Intelligence<br/>-  Supplier Strategie',
        ':FamilyServicesThirdText' : '<i style="color: #004A94;">"InnoChain Solutions has it all."</i>',      
        ':ITFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span>  advances information and communications technology to the next level alongside its procurement management systems and services. For you to experience procurement on the next level, we would like to share our IT products and services designed, innovated, and developed by our IT professionals to boost your digital business transactions with high and quality performance.',
        ':ITSecondText' : 'Coverage:<br/>-  E-Procurement<br/>-  E-Invoicing<br/>-  E-Commerce<br/>-  Cloud Computing Architecture<br/>-  Coding and Programming<br/>-  Software Development<br/>-  Web Teachnology<br/>-  Mobile Applications<br/>-  Testing and Systems Analysis<br/>-  Internal Server<br/>-  Network Administration<br/>-  Creative Digital Designing<br/>-  Technical Support',
        ':ITThirdText' : '<i style="color: #004A94;">"InnoChains Solutions is the global convergence of high IT experience."</i>',      
        ':ConsultingFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span>delivers you our procurement specialists to provide you objective, insightful, and useful advisory and inquiry services acquired from our years of experience and expertise in procurement and supply chain management.',
        ':ConsultingSecondText' : 'Covered Topics Could Be:<br/>-  Marketing<br/>-  E-Commerce<br/>-  Insurance<br/>-  Banking<br/>-  Real Estate<br/>-  Global Trade<br/>-  Professional Services<br/>-  Technology Value<br/>-  Procurement Management Benchmarking<br/>-  Performance Management Solutions<br/>-  Logistics, Facility Management, Marketing, Professional Services, Real State',
        ':ConsultingThirdText' : '<i style="color: #004A94;">"InnoChain Solutions takes your worries and delivers you the best possible advise."</i>',    
        ':HealthFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span>adheres to the fact that for success to keep flowing in different business transactions around the globe-- environmental, social, and economic factors that surround us and provide us with what we need and what should be taken care of. So InnoChain Solutions is strict in meeting regulatory requirements, to comply with laws, and to put forward ethical practices and moral systems among our employees, clients, suppliers, and the rest of the stakeholders we build relationships with. In this way, a sustainable procurement and supply chain management is achieved and extended where high benefits are at stake which include cost and risk reductions.',
        ':HealthSecondText' : '<i style="color: #004A94;">"InnoChain Solutions treats the environment and the society well, which leads to keeping the business work well and last long."</i>',    

    },
    'de': {
        ':ENG': 'DE',
        ':DE': 'EN',
        ':en': 'de',
        ':de': 'en',
        ':ENGM': 'DE',
        ':DEM': 'EN',
        ':enM': 'de',
        ':deM': 'en',
        ':home': 'Startseite',
        ':OurServices': 'Unsere Dienstleistungen',
        ':AboutUs': 'Über Uns',
        ':ContactUs': 'Kontaktiere Uns',
        ':homeM': 'Startseite',
        ':OurServicesM': 'Unsere Dienstleistungen',
        ':AboutUsM': 'Über Uns',
        ':ContactUsM': 'Kontaktiere Uns',
        ':herosubtitle': 'SOURCING-MANAGEMENT AUF',
        ':herosubtitleNL': 'HÖCHSTEM NIVEAU',
        ':heroparagraph': 'Wir lösen Probleme, Wir erledigen Dinge, Wir setzen den Trend im Beschaffungsmanagement',
        ':scroll': 'Scrollen',
        ':maintitle': 'ÜBER UNS',
        ':mainparagraph': 'Angesichts der Tatsache, dass das Zeitalter des Menschen die Welt mit dynamischen Fortschritten in Technologie und Dienstleistungen beherrscht, bietet <span style="color: #004A94;"> InnoChain Solutions (ICS)</span> die besten Beschaffungslösungen - unterstützt durch hochwertige Dienstleistungen im Bereich der Informations- und Kommunikationstechnologie.',
        ':Learnmore': 'Finde mehr heraus',
        ':fristcardtitle': 'Unsere Vision',
        ':fristcardtext': 'InnoChain Solutions sieht sich als wegweisender globaler Konvergenzpunkt bei der Bereitstellung von hochwertigen Beschaffungsmanagement-Dienstleistungen gebündelt mit einer hohen digitalen Integration. Unternehmen und Berufe verschiedenster Branchen sollen angeregt und aufgewertet werden - auf dem Weg zu Erfüllung, Wachstum und Erfolg.',
        ':secondcardtitle': 'Unser Ziel',
        ':secondcardtext': 'InnoChain Solutions versteht sich als ambitiösen anbieter von beschaffungslösungen, technologie-Upgrades und digitalen systemerweiterungen. Mit unseren Best-Practice-Ansätzen verwalten wir neue und frische proaktive herangehensweisen, um die unterschiedlichen Bedürfnisse und einzigartigen Anforderungen von start-ups, wachsenden unternehmen und etablierten unternehmen perfekt zu erfüllen - ohne Geld- und zeitverlust mit zu geringen Kosten durchgeführt werden.',
        ':thirdcardtitle': 'Unsere Marken',
        ':thirdcardtextleft': '- Digital und technologisch. <br/> - Schnell und weise.<br/> - Innovativ und kreativ.<br/> - Sicher und geborgen.<br/> - Vernünftig und wirtschaftlich.<br/> - Effizient und leistungsfähig.<br/> - Systematisch und strategisch.',
        ':thirdcardtextright': '- Funktionell und operativ.<br/> - Selbstbewusst und kompetent.<br/> - Kollaborativ und Operativ.<br/> - Zuverlässig und flexibel.<br/> - Bequem und komfortabel.<br/> - Nachhaltig und zugänglich.<br/> - Engagiert und diszipliniert.<br/>',
        ':servicestitle': 'UNSERE DIENSTLEISTUNGEN',
        ':SourcingManagementServices': 'Beschaffungsmanagement-<br/>Dienstleistungen',
        ':SourcingCommodities': 'Warenbeschaffung',
        ':FamilyOfficeServicesSourcing': 'Beschaffung von Family <br/> Office-Diensten',
        ':ITServices': 'IT-Dienstleistungen',
        ':ConsultingServices': 'Beratungsdienste',
        ':HealthCare': 'Gesundheitswesen',
        ':ContactUS': 'Kontaktiere uns',
        ':Contactinfo': 'Kontakt info',
        ':Message': 'Nachricht',
        ':submit': 'Einreichen',
        ':AboutUsTitle' : 'Über uns',
        ':FristAboutText' : '<span style="font-size: 30px; color: #004A94;">InnoChain Solutions (ICS) </span> ist ein unabhängiges privates Unternehmen, das durch die Zusammenarbeit von Spezialisten für Beschaffungsdienstleistungen und Technologie-Experten von Spitzenunternehmen aus der ganzen Welt besteht. Mit unserer Erfahrung und unseren langjährigen Beziehungen in den jeweiligen Berufsfeldern sind wir bestens gerüstet umfassende, innovative und qualitativ hochwertige Ende-to-End-Beschaffungslösungen zu bieten, die auf unterschiedlichste Anforderungen und Bedürfnisse zugeschnitten sind.',
        ':SecondAboutText' : '<i>"Das Unternehmen InnoChain Solutions ist eine Zusammenarbeit von Beschaffungsspezialisten und Experten für digitale Technologie auf der ganzen Welt."<br/> - ICS-Exekutivpräsident. -</i>',
        ':ManagementServicesFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span> investiert in eine Vielzahl von Beschaffungsdienstleistungen. Mit unserem breiten Fachwissen, unserem tiefen Wissen und unserer ständigen Innovation sind wir bestrebt, unseren Kunden voll integrierte Beschaffungsmanagementdienste anzubieten. Um Ihnen eine vollständige Source-to-Settle- und End-to-End-Lösung zu bieten, die zu einem effizienten Betriebssystem und erheblichen Produktionsgewinnen führt, die zu optimalen Kostenvorteilen und Kosteneinsparungen führen.',
        ':ManagementServicesSecondText' : 'Abdeckung:<br/> - Lieferketten-Management<br/> - Lieferanten-Netzwerke<br/> - Beschaffung<br/> - Rohstoffe<br/> - Dienstleistungen und indirekte Ausgaben',
        ':ManagementServicesThirdText' : '<i style="color: #004A94;">"InnoChain Solutions erkennt die fehlenden Glieder und die schwachen Einheiten, die Ihr Unternehmen daran hindern, reibungslos zu laufen und in Arbeit zu sein."</i>',
        ':SourcingFirstText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span> wahrt seinen Ruf und stärkt seine Beziehungen mit verschiedenen globalen Industrien, um Kunden besser bedienen zu können. Mit unserem Fachwissen im Bereich Warenbeschaffung unterstützen wir unsere Kunden dabei, stressfrei zu arbeiten, Termine einzuhalten und sich auf kritische Teile des Geschäfts zu konzentrieren. ',
        ':SourcingSecondText' : 'Abdeckung:<br/>- Landwirtschaft<br/>- Energie<br/>- Metalle<br/>- Viehzucht<br/>- Logistik',
        ':SourcingThirdText' : '<i style="color: #004A94;">"InnoChain Solutions verfügt über breite und starke Geschäftsverbindungen rund um den Globus, um Ihnen die idealen Lösungen anbieten zu können."</i>',    
        ':FamilyServicesFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span> besteht aus flexiblen und vernetzten Geschäftsintelligenzen, die auf innovative Weise die perfekt passenden und massgeschneiderten Dienstleistungen, Strategien und Lösungen für unsere Kunden ausfindig machen und neue Wege finden, damit Sie mehr Wert aus der Lieferkette herausholen können.',
        ':FamilyServicesSecondText' : 'Abdeckung:<br/>- Nachfrage-Management<br/>- Strategien für die Beschaffung<br/>- Best Practice bei der Beschaffung<br/>- Supply Chain Management<br/>- Marktbewertungen<br/>- Kategorie Intelligenz<br/>- Lieferantenstrategie',
        ':FamilyServicesThirdText' : '<i style="color: #004A94;">"InnoChain Solutions hat alles."</i>',    
        ':ITFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span> bietet Informations- und Kommunikationstechnologie gemeinsam mit Beschaffungsdienstleistungen aus einer Hand. Damit Sie ein Beschaffungswesen auf höchstem Niveau erleben können, möchten wir Ihnen unsere IT-Produkte- und -Dienstleistungspalette vorstellen, die von unseren IT-Fachleuten entworfen und entwickelt werden, um Ihre digitalen Geschäftstransaktionen mit qualitativ hochwertiger Leistung zu unterstützen.',
        ':ITSecondText' : 'Abdeckung:<br/>- E-Beschaffung<br/>- E-Invoicing<br/>- E-Commerce<br/>- Cloud Computing-Architektur<br/>- Codierung und Programmierung<br/>- Software-Entwicklung<br/>- Web-Lehrtechnik<br/>- Mobile Anwendungen<br/>- Testen und Systemanalyse<br/>- Interner Server<br/>- Netzwerk-Verwaltung<br/>- Kreatives digitales Design<br/>- Technischer Support',
        ':ITThirdText' : '<i style="color: #004A94;">"InnoChains Solutions ist die globale Konvergenz von hoher IT-Erfahrung."</i>',    
        ':ConsultingFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span>stellt Ihnen unsere Beschaffungsspezialisten zur Verfügung, um Ihnen objektive, aufschlussreiche und nützliche Beratungs- und Auskunftsdienste zu bieten, die auf unserer jahrelangen Erfahrung und Expertise im Bereich Beschaffung und Supply Chain Management basieren.',
        ':ConsultingSecondText' : 'Abgedeckte Themen könnten sein:<br/>- Vermarktung<br/>- E-Commerce<br/>- Versicherung<br/>- Bankwesen<br/>- Immobilien<br/>- Globaler Handel<br/>- Professionelle Dienstleistungen<br/>- Wert der Technologie<br/>- Benchmarking des Beschaffungsmanagements<br/>- Performance-Management-Lösungen<br/>- Logistik, Gebäudemanagement, Marketing, professionelle Dienstleistungen, Real State',
        ':ConsultingThirdText' : '<i style="color: #004A94;">"InnoChain Solutions nimmt Ihre Sorgen auf und bietet Ihnen die bestmögliche Beratung."</i>',    
        ':HealthFristText' : '<span style="color: #004A94;">InnoChain Solutions (ICS) </span>hält sich an die Tatsache, dass für den Erfolg in verschiedenen Geschäftsvorgängen rund um den Globus - ökologische, soziale und wirtschaftliche Faktoren, die uns umgeben und uns mit dem versorgen, was wir brauchen und worum wir uns kümmern sollten - weiter fließen müssen. Deshalb ist InnoChain Solutions streng darauf bedacht, die behördlichen Anforderungen zu erfüllen, die Gesetze einzuhalten und ethische Praktiken und Moralsysteme unter unseren Mitarbeitern, Kunden, Lieferanten und den übrigen Stakeholdern, mit denen wir Beziehungen aufbauen, vorzuschlagen. Auf diese Weise wird ein nachhaltiges Beschaffungs- und Lieferkettenmanagement erreicht und dort erweitert, wo ein hoher Nutzen auf dem Spiel steht, zu dem auch Kosten- und Risikominderungen gehören.',
        ':HealthSecondText' : '<i style="color: #004A94;">"InnoChain Solutions behandelt die Umwelt und die Gesellschaft gut, was dazu führt, dass das Geschäft erhalten bleibt gut arbeiten und lange dauern. "</i>',    



    }
};
